### ISSUE TITLE
Slider style doesn't work

### ISSUE THREAD

**Issue by Gamble-Man** [thewebverse/magento2-theme-ten#21]
I copied your _slider-primary.less file into my theme, but the slider didn't work, I followed the steps in your video, turned on developer mode and deleted the static files

**Comment by thewebverse** [comment]
Please try again following these steps:

1. Create a new file named _slider-primary.less inside <theme>/web/css/source/sections directory. (Add the same code as in this repository)
2. Make sure to import _slider-primary.less file inside _extend.less file using: @import 'sections/_slider-primary'; (Same code as in this repository) 

At this moment you are creating a new .less file and making sure that this file is included in the themes code base.

3. Using Page Builder from admins panel edit the Slider Content Type and inside the field CSS Classes add this class: slider-primary

At this moment the styles from _slider-primary.less will be applied to the Slider element.

Make sure to regenerate static files so LESS is compiled to CSS.

**Comment by Gamble-Man** [comment]
> Please try again following these steps:
> 
> 1. Create a new file named _slider-primary.less inside /web/css/source/sections directory. (Add the same code as in this repository)
> 2. Make sure to import _slider-primary.less file inside _extend.less file using: @import 'sections/_slider-primary'; (Same code as in this repository)
> 
> At this moment you are creating a new .less file and making sure that this file is included in the themes code base.
> 
> 3. Using Page Builder from admins panel edit the Slider Content Type and inside the field CSS Classes add this class: slider-primary
> 
> At this moment the styles from _slider-primary.less will be applied to the Slider element.
> 
> Make sure to regenerate static files so LESS is compiled to CSS.



> Please try again following these steps:
> 
> 1. Create a new file named _slider-primary.less inside /web/css/source/sections directory. (Add the same code as in this repository)
> 2. Make sure to import _slider-primary.less file inside _extend.less file using: @import 'sections/_slider-primary'; (Same code as in this repository)
> 
> At this moment you are creating a new .less file and making sure that this file is included in the themes code base.
> 
> 3. Using Page Builder from admins panel edit the Slider Content Type and inside the field CSS Classes add this class: slider-primary
> 
> At this moment the styles from _slider-primary.less will be applied to the Slider element.
> 
> Make sure to regenerate static files so LESS is compiled to CSS.

I have solved the problem, the reason is that I used a different filename, thank you very much, I love your design
